/**
 * The contributor globe.
 *
 * PROVENANCE -- DO NOT HAND-EDIT
 * ------------------------------
 * Generated by scripts/extract_globe_module.py from the JavaScript that
 * src/components/globe.py emits. It was extracted from that module's real
 * output rather than retyped, so the drawing, interaction and accessibility
 * behaviour is unchanged: 6 deg/s auto-rotation that respects
 * prefers-reduced-motion, pointer-capture drag with inertia and a +/-75 degree
 * pitch clamp, a 3 s auto-resume, keyboard arrows, IntersectionObserver and
 * visibility pausing, and a device-pixel-ratio capped at 2.
 *
 * WHAT A MARKER IS ALLOWED TO BE
 * ------------------------------
 * lat, lng, label, country, count, layer -- and nothing else. No user id, no
 * email, no timestamp, no sub-country coordinate. The coordinates are country
 * centroids exactly, computed server-side by worker/lib/geo.js; `country` is
 * the ISO 3166-1 alpha-2 code, which is what selects the shape to fill.
 * The browser Geolocation API is never called, and no IP address exists
 * anywhere in this path to be revealed.
 */

import * as geo from "d3-geo";
import * as topojson from "topojson-client";
import { COUNTRY_MAP_IDS } from "./country-ids.js";

/**
 * Collapse the two layers into one marker per country, keeping both counts.
 *
 * Ported from _merge_country_markers in src/components/globe.py. One country
 * gets one dot; the tooltip still distinguishes registrations from approved
 * contributors.
 */
export function mergeCountryMarkers(markers) {
  const countries = new Map();
  for (const marker of markers) {
    const key = String(marker.label).toLowerCase();
    if (!countries.has(key)) {
      countries.set(key, {
        lat: marker.lat,
        lng: marker.lng,
        label: marker.label,
        signupCount: 0,
        contributorCount: 0,
      });
    }
    const entry = countries.get(key);
    const field = marker.layer === "contributor" ? "contributorCount" : "signupCount";
    entry[field] += marker.count;
  }
  return [...countries.values()];
}

/**
 * The rotation that puts the busiest country in view.
 *
 * Ported from _initial_focus: the largest marker wins, and a contributor
 * marker wins an exact tie, which keeps the more meaningful activity visible
 * without hiding a larger registered-user community.
 */
function initialRotation(markers) {
  if (!markers.length) return [0, 0, 0];
  let best = markers[0];
  for (const marker of markers) {
    const count = Number(marker.count) || 0;
    const bestCount = Number(best.count) || 0;
    const isContributor = marker.layer === "contributor";
    const bestIsContributor = best.layer === "contributor";
    if (count > bestCount || (count === bestCount && isContributor && !bestIsContributor)) {
      best = marker;
    }
  }
  return [-Number(best.lng), -Number(best.lat), 0];
}

/**
 * Draw the globe into `root`, which must already contain the markup.
 *
 * Returns a teardown function. The animation frame and observers would
 * otherwise keep running after the page routes away, which on a
 * client-side-routed site means a canvas nobody can see still burning a frame
 * every 16 ms.
 */
export function mountGlobe(root, options = {}) {
  const MARKERS = options.markers || [];
  const DISPLAY_MARKERS = mergeCountryMarkers(MARKERS);
  const WORLD = options.world || null;
  const AUTO_ROTATE = options.autoRotate !== false;
  const height = options.height || 460;
  root.style.height = height + "px";
  const rootWrap = root.querySelector("#globe-wrap");
  if (rootWrap) rootWrap.style.height = height + "px";



  // ── Canvas setup ──────────────────────────────────────────────────────────
  const canvas = root.querySelector('#globe');
  const tooltip = root.querySelector('#tooltip');
  const wrap  = root.querySelector('#globe-wrap');
  const DPR = Math.min(window.devicePixelRatio || 1, 2);

  function measureSize() {
    const avail = Math.min(wrap.clientWidth, height - 44);
    return Math.max(160, avail);
  }

  function applyCanvasSize(size) {
    canvas.style.width  = size + 'px';
    canvas.style.height = size + 'px';
    canvas.width  = size * DPR;
    canvas.height = size * DPR;
  }

  let SIZE = measureSize();
  applyCanvasSize(SIZE);
  const ctx = canvas.getContext('2d');
  ctx.scale(DPR, DPR);

  // ── Projection ────────────────────────────────────────────────────────────
  // d3geo is the UMD namespace from d3-geo.umd.min.js
  const d3geo = geo;  // an imported module here, formerly a UMD global
  let projection, pathGen, graticule, sphere;

  function initProjection() {
    projection = d3geo.geoOrthographic()
      .scale(SIZE / 2 - 4)
      .translate([SIZE / 2, SIZE / 2])
      .clipAngle(90)
      .precision(0.2)
      .rotate([ROT[0], ROT[1], ROT[2]]);
    // Bind the canvas path to the orthographic projection. Without this,
    // GeoJSON Sphere objects are streamed directly to the canvas context,
    // which has no sphere() method and crashes every animation frame.
    pathGen  = d3geo.geoPath(projection).context(ctx);
    graticule = d3geo.geoGraticule()();
    sphere    = { type: 'Sphere' };
  }

  // ── World geometry ────────────────────────────────────────────────────────
  let land = null, borders = null, countries = [];
  if (WORLD) {
    try {
      land    = topojson.feature(WORLD, WORLD.objects.land);
      countries = topojson.feature(WORLD, WORLD.objects.countries).features;
      // countries mesh for borders (no shared edges between countries)
      borders = topojson.mesh(WORLD, WORLD.objects.countries,
                              (a, b) => a !== b);
    } catch(e) { console.warn('topojson parse error', e); }
  }

  // Resolve each country marker to its map polygon once, by country code
  // rather than by geometry. Asking which polygon contained a marker's
  // coordinate answered a question about identity with a point-in-polygon
  // test, and got it wrong: Belgium's marker filled France, and Singapore's
  // fills Malaysia even from a perfect centroid. See country-ids.js.
  const activeCountries = countries.map(feature => {
    const activity = MARKERS.filter(
      marker => COUNTRY_MAP_IDS[marker.country] === String(feature.id)
    );
    if (!activity.length) return null;
    return {
      feature,
      hasContributor: activity.some(marker => marker.layer === 'contributor'),
    };
  }).filter(Boolean);

  // ── Rotation state ────────────────────────────────────────────────────────
  let ROT    = initialRotation(MARKERS); //ORIGINAL: [95.7,-37.1,0]; // starts on strongest activity
  let VEL    = [0, 0];        // [dLambda/ms, dPhi/ms]
  const INERTIA_DECAY = 0.94; // per frame at 60fps ≈ 0.94^60 ≈ 0.025 after 1 s

  // ── Drag state ────────────────────────────────────────────────────────────
  let dragging  = false;
  let lastPt    = null;
  let lastPtT   = 0;
  let prevPt    = null;
  let prevPtT   = 0;

  // ── Auto-rotate ───────────────────────────────────────────────────────────
  const AUTO_DEG_PER_S  = 6.0;
  let autoActive        = AUTO_ROTATE;
  let idleTimer         = null;
  let resumeEased       = 0; // 0→1 ease-in multiplier after resume
  const RESUME_DELAY_MS = 3000;
  const RESUME_EASE_MS  = 1200;

  function pauseAuto() {
    autoActive  = false;
    resumeEased = 0;
    clearTimeout(idleTimer);
    if (AUTO_ROTATE) {
      idleTimer = setTimeout(() => {
        autoActive  = true;
        resumeEased = 0;
      }, RESUME_DELAY_MS);
    }
  }

  // ── RAF loop ──────────────────────────────────────────────────────────────
  let lastTime = null;
  let rafId    = null;
  let visible  = true; // IntersectionObserver

  // prefers-reduced-motion: no auto-rotation (manual drag still works)
  const prefersReduced =
    window.matchMedia('(prefers-reduced-motion: reduce)').matches;

  function tick(now) {
    rafId = requestAnimationFrame(tick);
    if (!visible) return;

    const dt = lastTime === null ? 16 : Math.min(now - lastTime, 64);
    lastTime = now;

    if (!dragging) {
      // Apply inertia
      if (Math.abs(VEL[0]) > 1e-5 || Math.abs(VEL[1]) > 1e-5) {
        ROT[0] += VEL[0] * dt;
        ROT[1]  = clampPhi(ROT[1] + VEL[1] * dt);
        const decay = Math.pow(INERTIA_DECAY, dt / 16.67);
        VEL[0] *= decay;
        VEL[1] *= decay;
        if (Math.abs(VEL[0]) < 1e-5) VEL[0] = 0;
        if (Math.abs(VEL[1]) < 1e-5) VEL[1] = 0;
      }

      // Auto-rotation
      if (AUTO_ROTATE && autoActive && !prefersReduced) {
        if (resumeEased < 1) resumeEased = Math.min(1, resumeEased + dt / RESUME_EASE_MS);
        const speed = AUTO_DEG_PER_S * resumeEased;
        ROT[0] += speed * dt / 1000;
      }
    }

    ROT[0] = ((ROT[0] + 180) % 360) - 180; // keep in [-180, 180]
    draw(dt);
  }

  // ── Drawing ───────────────────────────────────────────────────────────────
  function draw(dt) {
    ctx.clearRect(0, 0, SIZE, SIZE);
    projection.rotate([ROT[0], ROT[1], ROT[2]]);
    pathGen  = d3geo.geoPath(projection).context(ctx);

    // Ocean sphere with radial gradient for depth
    const grad = ctx.createRadialGradient(
      SIZE * 0.42, SIZE * 0.36, 0,
      SIZE / 2,    SIZE / 2,    SIZE / 2
    );
    grad.addColorStop(0,   '#d8eaf6');
    grad.addColorStop(0.7, '#b6cfdf');
    grad.addColorStop(1,   '#8fb3c8');

    ctx.beginPath(); pathGen(sphere);
    ctx.fillStyle = grad; ctx.fill();

    // Land
    if (land) {
      ctx.beginPath(); pathGen(land);
      ctx.fillStyle = '#cdbf9e'; ctx.fill();
    }

    // Fill countries represented in the community data. Contributor activity
    // takes the green layer; countries with registrations only use amber.
    activeCountries.forEach(country => {
      ctx.beginPath(); pathGen(country.feature);
      ctx.fillStyle = country.hasContributor
        ? 'rgba(46,107,71,0.78)'
        : 'rgba(232,168,80,0.76)';
      ctx.fill();
      ctx.strokeStyle = country.hasContributor ? '#1e4830' : '#ad6c12';
      ctx.lineWidth = 1.15;
      ctx.stroke();
    });

    // Graticule (subtle)
    ctx.beginPath(); pathGen(graticule);
    ctx.strokeStyle = 'rgba(255,255,255,0.22)';
    ctx.lineWidth   = 0.45; ctx.stroke();

    // Country borders
    if (borders) {
      ctx.beginPath(); pathGen(borders);
      ctx.strokeStyle = 'rgba(160,148,120,0.7)';
      ctx.lineWidth   = 0.5; ctx.stroke();
    }

    // Globe outline
    ctx.beginPath(); pathGen(sphere);
    ctx.strokeStyle = 'rgba(90,120,150,0.35)';
    ctx.lineWidth   = 1.2; ctx.stroke();

    // Atmosphere glow at limb
    const atmo = ctx.createRadialGradient(
      SIZE/2, SIZE/2, SIZE/2 - 2,
      SIZE/2, SIZE/2, SIZE/2 + 10
    );
    atmo.addColorStop(0, 'rgba(200,225,255,0)');
    atmo.addColorStop(1, 'rgba(200,225,255,0.30)');
    ctx.beginPath();
    ctx.arc(SIZE/2, SIZE/2, SIZE/2 + 10, 0, Math.PI * 2);
    ctx.fillStyle = atmo; ctx.fill();

    // Directional light overlay (upper-left)
    const light = ctx.createRadialGradient(
      SIZE * 0.38, SIZE * 0.32, 0,
      SIZE / 2,    SIZE / 2,    SIZE / 2
    );
    light.addColorStop(0,   'rgba(255,252,244,0.20)');
    light.addColorStop(0.55,'rgba(255,252,244,0.03)');
    light.addColorStop(1,   'rgba(0,0,0,0.10)');
    ctx.beginPath(); pathGen(sphere);
    ctx.fillStyle = light; ctx.fill();

    // One marker per country. Contributor countries use the green layer;
    // registration-only countries use amber.
    drawMarkers();
  }

  function visibleMarkerPoint(m) {
      const centre = projection.invert([SIZE / 2, SIZE / 2]);
      if (!centre || d3geo.geoDistance([m.lng, m.lat], centre) >= Math.PI / 2) return null;
      const pt = projection([m.lng, m.lat]);
      return pt && pt[0] !== null ? pt : null;
  }

  function drawMarkers() {
    DISPLAY_MARKERS.forEach(m => {
      const pt = visibleMarkerPoint(m);
      if (!pt) return;

      const count = m.contributorCount || m.signupCount;
      const contributor = m.contributorCount > 0;
      const r = Math.min(3 + Math.sqrt(count) * 1.6, 14);

      ctx.save();
      ctx.beginPath();
      ctx.arc(pt[0], pt[1], r, 0, Math.PI * 2);
      ctx.fillStyle   = contributor ? '#2e6b47cc' : '#e8a850cc';
      ctx.fill();
      ctx.strokeStyle = contributor ? '#1e4830' : '#c8831a';
      ctx.lineWidth   = 1.2;
      ctx.stroke();
      ctx.restore();
    });
  }

  // ── Pointer Events ────────────────────────────────────────────────────────
  canvas.addEventListener('pointerdown', e => {
    e.preventDefault();
    canvas.setPointerCapture(e.pointerId);
    dragging = true;
    pauseAuto();
    VEL = [0, 0];
    lastPt  = [e.clientX, e.clientY];
    lastPtT = performance.now();
    prevPt  = lastPt;
    prevPtT = lastPtT;
  });

  canvas.addEventListener('pointermove', e => {
    const pt = [e.clientX, e.clientY];

    // Tooltip when not dragging
    if (!dragging) {
      updateTooltip(e);
    }

    if (!dragging || !lastPt) return;
    e.preventDefault();

    const now  = performance.now();
    const dLam = (pt[0] - lastPt[0]) / SIZE * 180;
    const dPhi = (pt[1] - lastPt[1]) / SIZE * 180;

    ROT[0]  = ((ROT[0] + dLam + 180) % 360) - 180;
    ROT[1]  = clampPhi(ROT[1] - dPhi);

    const dtSeg = now - prevPtT;
    if (dtSeg > 8) {
      VEL[0] =  (pt[0] - prevPt[0]) / SIZE * 180 / dtSeg;
      VEL[1] = -(pt[1] - prevPt[1]) / SIZE * 180 / dtSeg;
      prevPt  = lastPt;
      prevPtT = lastPtT;
    }

    lastPt  = pt;
    lastPtT = now;
  });

  canvas.addEventListener('pointerup', () => {
    dragging = false;
    lastPt   = null;
    pauseAuto();
  });

  canvas.addEventListener('pointercancel', () => {
    dragging = false; lastPt = null; VEL = [0, 0];
  });

  canvas.addEventListener('mouseleave', () => {
    tooltip.style.display = 'none';
  });

  // ── Tooltip ───────────────────────────────────────────────────────────────
  function updateTooltip(e) {
    const rect  = canvas.getBoundingClientRect();
    const mx    = e.clientX - rect.left;
    const my    = e.clientY - rect.top;
    let   closest = null;
    let   minDist = 18;  // pixel hit radius

    DISPLAY_MARKERS.forEach(m => {
      const pt = visibleMarkerPoint(m);
      if (!pt) return;
      const dist = Math.hypot(mx - pt[0], my - pt[1]);
      if (dist < minDist) { minDist = dist; closest = m; }
    });

    if (closest) {
      const parts = [];
      if (closest.signupCount) parts.push(
        closest.signupCount + ' registered user' + (closest.signupCount === 1 ? '' : 's')
      );
      if (closest.contributorCount) parts.push(
        closest.contributorCount + ' approved contributor' +
        (closest.contributorCount === 1 ? '' : 's')
      );
      tooltip.textContent = closest.label + ': ' + parts.join(' · ');
      tooltip.style.display = 'block';
      // Clamp so tooltip stays inside the wrapper
      const tx = Math.min(mx + 12, SIZE - tooltip.offsetWidth - 4);
      const ty = Math.max(my - 28, 2);
      tooltip.style.left = tx + 'px';
      tooltip.style.top  = ty + 'px';
    } else {
      tooltip.style.display = 'none';
    }
  }

  // ── Keyboard ──────────────────────────────────────────────────────────────
  canvas.addEventListener('keydown', e => {
    const NUDGE = 5;
    switch(e.key) {
      case 'ArrowLeft':  ROT[0] -= NUDGE; break;
      case 'ArrowRight': ROT[0] += NUDGE; break;
      case 'ArrowUp':    ROT[1] = clampPhi(ROT[1] - NUDGE); break;
      case 'ArrowDown':  ROT[1] = clampPhi(ROT[1] + NUDGE); break;
      default: return;
    }
    e.preventDefault();
    pauseAuto();
  });

  // ── Visibility & Intersection pausing ────────────────────────────────────
  function handleVisibilityChange() {
    visible = document.visibilityState !== 'hidden';
    if (visible && lastTime !== null) lastTime = null;
  }
  document.addEventListener('visibilitychange', handleVisibilityChange);

  let intersectionObserver = null;
  if (window.IntersectionObserver) {
    intersectionObserver = new IntersectionObserver(entries => {
      visible = entries[0].isIntersecting;
      if (visible && lastTime !== null) lastTime = null;
    }, { threshold: 0.1 });
    intersectionObserver.observe(canvas);
  }

  function handleResize() {
    const nextSize = measureSize();
    if (nextSize === SIZE) return;
    SIZE = nextSize;
    applyCanvasSize(SIZE);
    ctx.setTransform(DPR, 0, 0, DPR, 0, 0);
    initProjection();
    draw(0);
  }

  let resizeObserver = null;
  if (window.ResizeObserver) {
    resizeObserver = new ResizeObserver(handleResize);
    resizeObserver.observe(wrap);
  } else {
    window.addEventListener('resize', handleResize);
  }

  // ── Helpers ───────────────────────────────────────────────────────────────
  function clampPhi(p) { return Math.max(-75, Math.min(75, p)); }

  // ── Init ──────────────────────────────────────────────────────────────────
  initProjection();
  rafId = requestAnimationFrame(tick);


  return function teardown() {
    if (rafId) cancelAnimationFrame(rafId);
    if (idleTimer) clearTimeout(idleTimer);
    if (resizeObserver) resizeObserver.disconnect();
    else window.removeEventListener("resize", handleResize);
    if (intersectionObserver) intersectionObserver.disconnect();
    document.removeEventListener("visibilitychange", handleVisibilityChange);
  };
}
