"""Carry src/theme.py's stylesheet across to the standalone frontend.

WHY THIS IS FILTERED RATHER THAN COPIED
---------------------------------------
`src/theme.py` injects one stylesheet into Streamlit. Roughly a fifth of its
rules exist only to fight Streamlit's own chrome -- `[data-testid=...]`,
`.stApp`, sidebar widths, block padding. Those selectors match nothing on a
static site, and copying them would leave a reader unable to tell which rules
are load-bearing and which are archaeology.

So the rules that target Streamlit internals are dropped and everything else is
kept verbatim: the `:root` design tokens, the `.onnm-*` component rules that are
the actual visual identity, and the element-level typography.

    python scripts/extract_theme_css.py

The Google Fonts link that theme.py injects separately is emitted as an @import
at the top, because the standalone page has no equivalent injection point.
"""

from __future__ import annotations

import importlib.util
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
OUT = REPO / "web" / "src" / "styles" / "theme.css"

#: A rule is dropped when its selector mentions any of these. All of them are
#: Streamlit DOM that does not exist once Streamlit is gone.
STREAMLIT_MARKERS = (
    "data-testid",
    ".stApp",
    ".stMain",
    ".stSidebar",
    ".stButton",
    ".stDownloadButton",
    ".stFileUploader",
    ".stTextInput",
    ".stCheckbox",
    ".stSelectbox",
    ".stSlider",
    ".stExpander",
    ".stAlert",
    ".stMarkdown",
    ".stTabs",
    ".stSpinner",
    ".stForm",
    ".st-",
    "section[",
    "iframe",
)

HEADER = """/*
 * ONNM visual identity.
 *
 * GENERATED by scripts/extract_theme_css.py from src/theme.py -- do not
 * hand-edit. Rules whose selectors targeted Streamlit's own DOM have been
 * dropped; everything else is verbatim, so the palette, the type scale and the
 * .onnm-* components are the same ones the Streamlit app shipped.
 *
 * The warm ivory ground (#f7f4ef) against sterile white task surfaces
 * (#ffffff) is deliberate: the reading surface should not look like the image
 * under examination.
 */

"""

BASE = """

/* ---------------------------------------------------------------------------
 * Standalone base.
 *
 * Streamlit supplied a document skeleton -- box sizing, body background, a
 * centred column with padding. None of that exists now, so it is stated here.
 * These rules are new; everything above this comment came from theme.py.
 * ------------------------------------------------------------------------ */

*,
*::before,
*::after { box-sizing: border-box; }

html { -webkit-text-size-adjust: 100%; }

body {
  margin: 0;
  background: var(--bg, #f7f4ef);
  color: var(--ink, #1c1a17);
  font-family: "Inter", "Segoe UI", "Helvetica Neue", Arial, sans-serif;
  font-size: 16px;
  line-height: 1.55;
  -webkit-font-smoothing: antialiased;
}

.onnm-shell {
  max-width: 1100px;
  margin: 0 auto;
  padding: 0 24px 72px;
}

/* A visible focus ring is a requirement, not a preference: this application is
 * operated by keyboard by anyone using a screen reader, and the globe itself is
 * keyboard-navigable. */
:focus-visible {
  outline: 2px solid #1a56db;
  outline-offset: 2px;
  border-radius: 4px;
}

/* Honour the same motion preference the globe honours. */
@media (prefers-reduced-motion: reduce) {
  *, *::before, *::after {
    animation-duration: 0.01ms !important;
    animation-iteration-count: 1 !important;
    transition-duration: 0.01ms !important;
    scroll-behavior: auto !important;
  }
}
"""


def split_rules(css: str) -> list[tuple[str, str]]:
    """Split a flat stylesheet into (selector, body) pairs, keeping @-blocks whole."""
    rules: list[tuple[str, str]] = []
    depth = 0
    start = 0
    selector_end = None
    for i, char in enumerate(css):
        if char == "{":
            if depth == 0:
                selector_end = i
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                selector = css[start:selector_end]
                body = css[selector_end : i + 1]
                rules.append((selector, body))
                start = i + 1
    return rules


def main() -> int:
    spec = importlib.util.spec_from_file_location("onnm_theme", REPO / "src" / "theme.py")
    module = importlib.util.module_from_spec(spec)
    sys.modules["onnm_theme"] = module
    spec.loader.exec_module(module)

    css = module._CSS
    kept: list[str] = []
    dropped = 0

    for selector, body in split_rules(css):
        flat = " ".join(selector.split())
        if any(marker in flat for marker in STREAMLIT_MARKERS):
            dropped += 1
            continue
        if not flat:
            continue
        kept.append(f"{flat} {body.strip()}")

    fonts = re.search(r'href="([^"]*fonts\.googleapis[^"]*)"', module._GOOGLE_FONTS_LINK)
    import_line = f'@import url("{fonts.group(1)}");\n\n' if fonts else ""

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(HEADER + import_line + "\n\n".join(kept) + BASE, encoding="utf-8")

    print(f"wrote {OUT.relative_to(REPO)}")
    print(f"  kept    {len(kept)} rules")
    print(f"  dropped {dropped} Streamlit-only rules")
    return 0


if __name__ == "__main__":
    sys.exit(main())
