"""Turn the globe JavaScript in src/components/globe.py into a real ES module.

WHY THIS IS A SCRIPT AND NOT A ONE-OFF EDIT
-------------------------------------------
`src/components/globe.py` emits ~385 lines of JavaScript as a Python string.
That code is the product of a lot of careful work -- pointer-capture dragging,
inertia, the pitch clamp, visibility pausing -- and retyping it into a .js file
would be an invitation to introduce a subtle behavioural difference that no test
would catch.

So the module is generated: the Python is executed, its real output captured,
and only the parts that must change for a module context are rewritten. Every
substitution below is asserted, so if the Python is edited in a way that moves
one of these lines, this script fails loudly instead of emitting something
subtly wrong.

    python scripts/extract_globe_module.py

Run it again after changing the globe in Python, and commit the result.
"""

from __future__ import annotations

import importlib.util
import json
import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
OUT = REPO / "web" / "src" / "globe" / "globe.js"
OUT_CSS = REPO / "web" / "src" / "globe" / "globe.css"
OUT_MARKUP = REPO / "web" / "src" / "globe" / "markup.html"

HEADER = '''/**
 * The contributor globe.
 *
 * PROVENANCE -- DO NOT HAND-EDIT
 * ------------------------------
 * Generated by scripts/extract_globe_module.py from the JavaScript that
 * src/components/globe.py emits. It was extracted from that module's real
 * output rather than retyped, so the drawing, interaction and accessibility
 * behaviour is unchanged: 6 deg/s auto-rotation that respects
 * prefers-reduced-motion, pointer-capture drag with inertia and a +/-75 degree
 * pitch clamp, a 3 s auto-resume, keyboard arrows, IntersectionObserver and
 * visibility pausing, and a device-pixel-ratio capped at 2.
 *
 * WHAT A MARKER IS ALLOWED TO BE
 * ------------------------------
 * lat, lng, label, count, layer -- and nothing else. No user id, no email, no
 * timestamp, no sub-country coordinate. The coordinates are country centroids
 * with a fixed per-country jitter applied server-side by worker/lib/geo.js.
 * The browser Geolocation API is never called, and no IP address exists
 * anywhere in this path to be revealed.
 */

import * as geo from "d3-geo";
import * as topojson from "topojson-client";

/**
 * Collapse the two layers into one marker per country, keeping both counts.
 *
 * Ported from _merge_country_markers in src/components/globe.py. One country
 * gets one dot; the tooltip still distinguishes registrations from approved
 * contributors.
 */
export function mergeCountryMarkers(markers) {
  const countries = new Map();
  for (const marker of markers) {
    const key = String(marker.label).toLowerCase();
    if (!countries.has(key)) {
      countries.set(key, {
        lat: marker.lat,
        lng: marker.lng,
        label: marker.label,
        signupCount: 0,
        contributorCount: 0,
      });
    }
    const entry = countries.get(key);
    const field = marker.layer === "contributor" ? "contributorCount" : "signupCount";
    entry[field] += marker.count;
  }
  return [...countries.values()];
}

/**
 * The rotation that puts the busiest country in view.
 *
 * Ported from _initial_focus: the largest marker wins, and a contributor
 * marker wins an exact tie, which keeps the more meaningful activity visible
 * without hiding a larger registered-user community.
 */
function initialRotation(markers) {
  if (!markers.length) return [0, 0, 0];
  let best = markers[0];
  for (const marker of markers) {
    const count = Number(marker.count) || 0;
    const bestCount = Number(best.count) || 0;
    const isContributor = marker.layer === "contributor";
    const bestIsContributor = best.layer === "contributor";
    if (count > bestCount || (count === bestCount && isContributor && !bestIsContributor)) {
      best = marker;
    }
  }
  return [-Number(best.lng), -Number(best.lat), 0];
}

/**
 * Draw the globe into `root`, which must already contain the markup.
 *
 * Returns a teardown function. The animation frame and observers would
 * otherwise keep running after the page routes away, which on a
 * client-side-routed site means a canvas nobody can see still burning a frame
 * every 16 ms.
 */
export function mountGlobe(root, options = {}) {
  const MARKERS = options.markers || [];
  const DISPLAY_MARKERS = mergeCountryMarkers(MARKERS);
  const WORLD = options.world || null;
  const AUTO_ROTATE = options.autoRotate !== false;
  const height = options.height || 460;
  root.style.height = height + "px";
  const rootWrap = root.querySelector("#globe-wrap");
  if (rootWrap) rootWrap.style.height = height + "px";

'''

FOOTER = '''
  return function teardown() {
    if (rafId) cancelAnimationFrame(rafId);
    if (idleTimer) clearTimeout(idleTimer);
    if (resizeObserver) resizeObserver.disconnect();
    else window.removeEventListener("resize", handleResize);
    if (intersectionObserver) intersectionObserver.disconnect();
    document.removeEventListener("visibilitychange", handleVisibilityChange);
  };
}
'''

# Each pair is (must appear exactly once, replacement). Asserted, so a drift in
# globe.py surfaces here rather than as a silently different globe.
SUBSTITUTIONS = [
    (
        "const canvas = document.getElementById('globe');",
        "const canvas = root.querySelector('#globe');",
    ),
    (
        "const tooltip = document.getElementById('tooltip');",
        "const tooltip = root.querySelector('#tooltip');",
    ),
    (
        "const wrap  = document.getElementById('globe-wrap');",
        "const wrap  = root.querySelector('#globe-wrap');",
    ),
    (
        "const d3geo = window.d3geo || window.d3;",
        "const d3geo = geo;  // was the UMD global inside the Streamlit iframe",
    ),
    (
        "if (WORLD && typeof topojson !== 'undefined') {",
        "if (WORLD) {",
    ),
    (
        "let ROT    = ",
        "let ROT    = initialRotation(MARKERS); //ORIGINAL: ",
    ),
    (
        "const avail = Math.min(wrap.clientWidth, 460 - 44);",
        "const avail = Math.min(wrap.clientWidth, height - 44);",
    ),
]

# The source HTML is rendered inside an isolated Streamlit component iframe,
# where document-level selectors are safe. The Vite build mounts the same
# markup in the application document, so every selector must be constrained to
# the host or regeneration would once again lock the whole page to 460 px and
# reset unrelated canvas, legend and layout styles.
CSS_SELECTOR_SUBSTITUTIONS = [
    ("* {", ".onnm-globe-host,\n.onnm-globe-host * {"),
    ("html, body {", ".onnm-globe-host {"),
    ("#globe-wrap {", ".onnm-globe-host #globe-wrap {"),
    ("canvas {", ".onnm-globe-host canvas {"),
    ("canvas:active {", ".onnm-globe-host canvas:active {"),
    ("#tooltip {", ".onnm-globe-host #tooltip {"),
    ("#legend {", ".onnm-globe-host #legend {"),
    (".legend-item {", ".onnm-globe-host .legend-item {"),
    (".legend-dot {", ".onnm-globe-host .legend-dot {"),
]


def load_globe_module():
    spec = importlib.util.spec_from_file_location(
        "onnm_globe", REPO / "src" / "components" / "globe.py"
    )
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def main() -> int:
    globe = load_globe_module()

    html = globe._build_html(
        d3_script="/*__D3__*/",
        topojson_script="/*__TOPOJSON__*/",
        world_json='{"__WORLD__":1}',
        markers_json=json.dumps(globe.SAMPLE_MARKERS),
        auto_rotate=True,
        height=460,
    )
    lines = html.split("\n")

    def slice_between(open_tag: str, close_tag: str) -> list[str]:
        start = next(i for i, line in enumerate(lines) if open_tag in line)
        end = next(i for i, line in enumerate(lines) if close_tag in line and i > start)
        return lines[start + 1 : end]

    css = "\n".join(slice_between("<style>", "</style>")).strip()
    for old, new in CSS_SELECTOR_SUBSTITUTIONS:
        count = css.count(old)
        assert count == 1, f"expected exactly one CSS selector {old!r}, found {count}"
        css = css.replace(old, new, 1)
    # The app script is the LAST <script> block; the two before it are vendored.
    script_starts = [i for i, line in enumerate(lines) if line.strip().startswith("<script>")]
    app_start = script_starts[-1]
    app_end = next(i for i, line in enumerate(lines) if "</script>" in line and i > app_start)
    body_lines = lines[app_start + 1 : app_end]

    # Depth-tracked, because the legend nests three divs deep and matching the
    # first </div> would silently truncate the markup to half a legend.
    markup_start = next(i for i, line in enumerate(lines) if 'id="globe-wrap"' in line)
    depth = 0
    markup_end = None
    for i in range(markup_start, len(lines)):
        depth += lines[i].count("<div")
        depth -= lines[i].count("</div>")
        if depth == 0:
            markup_end = i
            break
    assert markup_end is not None, "globe-wrap div never closes"
    markup = lines[markup_start : markup_end + 1]

    # Drop the IIFE wrapper and the inlined data block: the module takes both as
    # arguments now. The data block ends at the AUTO_ROTATE line.
    body = "\n".join(body_lines)
    assert body.lstrip().startswith("(function()"), "expected an IIFE"
    auto_rotate_line = next(l for l in body_lines if "const AUTO_ROTATE" in l)
    body = body.split(auto_rotate_line, 1)[1]
    body = body.rsplit("})();", 1)[0]

    for old, new in SUBSTITUTIONS:
        count = body.count(old)
        assert count == 1, f"expected exactly one {old!r}, found {count}"
        body = body.replace(old, new, 1)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(HEADER + body + FOOTER, encoding="utf-8")
    OUT_CSS.write_text(css + "\n", encoding="utf-8")
    OUT_MARKUP.write_text("\n".join(markup).strip() + "\n", encoding="utf-8")

    print(f"wrote {OUT.relative_to(REPO)} ({len((HEADER + body + FOOTER).splitlines())} lines)")
    print(f"wrote {OUT_CSS.relative_to(REPO)} ({len(css.splitlines())} lines)")
    print(f"wrote {OUT_MARKUP.relative_to(REPO)} ({len(markup)} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
